#!/bin/sh

set -e

install_nixos() {
    if [ -f /etc/nixos/configuration.nix ] || [ -L /etc/nixos/configuration.nix ]
    then
        echo "Back up existing configuration..."
        sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.bak
    fi

    sudo ln -fs /home/excalibur/nixos-config/flake.nix /etc/nixos/flake.nix
    echo "Install profile completed!"

    RELEASE="24.05"
    sudo nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-${RELEASE} nixos
    sudo nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-unstable nixos-unstable
    sudo nix-channel --update
    echo "Update channel completed!"
}

install_nixOnDroid() {
    if [ -f "$HOME/.config/nixpkgs/nix-on-droid.nix" ] || [ -L "$HOME/.config/nixpkgs/nix-on-droid.nix" ]
    then
        echo "Back up existing configuration..."
        mv "$HOME/.config/nixpkgs/nix-on-droid.nix" "$HOME/.config/nixpkgs/nix-on-droid.nix.bak"
    fi
    if [ -d "$HOME/.config/nix-on-droid" ] || [ -d "$HOME/.config/nix-on-droid" ]
    then
        echo "Back up existing configuration..."
        mv "$HOME/.config/nix-on-droid" "$HOME/.config/nix-on-droid.bak"
    fi

    cd "$HOME"
    mv "$SCRIPT_DIR" "$HOME/.config/nix-on-droid"
    ln -fs "$HOME/.config/nix-on-droid" "$HOME/$(basename "$SCRIPT_DIR")"
    cd "$HOME/$(basename "$SCRIPT_DIR")"
    echo "Install profile completed!"

    RELEASE="24.05"
    nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-${RELEASE} nixpkgs
    nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-unstable nixpkgs-unstable
    nix-channel --update
    echo "Update channel completed!"

    echo "Install completed! Please run 'postinstall_setup' after you rebuild the system."
}

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

if [ -d /data/data/com.termux.nix/files/home ]; then
    install_nixOnDroid
else
    install_nixos
fi
