#!/bin/sh

set -e

if [ -f /etc/nixos/configuration.nix ] || [ -L /etc/nixos/configuration.nix ]
then
    echo "Back up existing configuration..."
    sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.bak
fi

sudo ln -s /home/excalibur/nixos-config/flake.nix /etc/nixos/flake.nix
echo "Install profile $1 completed!"
