#!/bin/sh

set -e

rebuild_nixos() {
    NIXOS_LABEL_VERSION="$(git rev-parse --short HEAD)"
    if [[ -n $(git status -s) ]]
    then
        NIXOS_LABEL_VERSION="${NIXOS_LABEL_VERSION}-dirty"
    fi
    export NIXOS_LABEL_VERSION

    sudo nixos-rebuild "$@"
}

rebuild_nixOnDroid() {
    device="${1:-$NOD_FLAKE_DEFAULT_DEVICE}"
    TERM=linux nix-on-droid --flake "$HOME/.config/nix-on-droid#$device" switch
}

if [ -d /data/data/com.termux.nix/files/home ]; then
    rebuild_nixOnDroid "$@"
else
    rebuild_nixos "$@"
fi
